Поправил стилистические шероховатости в первых двух главах
Infl1ght/skunk_works pull request #11
Opened 2020-10-17 07:55 UTC by Atarity

2020-10-21 19:30 UTC, Atarity commented
@Infl1ght То ли в оригинале неточность, то ли лыжи не катят. В английской версии `...over Tyuratam, the big Russian missile test center deep in the Urals`. Тюратам это современный Байконур. И где Байконур, а где deep in the Urals... 🤔

2020-11-09 12:00 UTC, Infl1ght commented
@Atarity  В английской версии очень много подобных неточностей, и это легко объяснимо - книга написана в 1994 году, когда интернет был скорее диковинкой, чем инструментом. Я решил специально оставить все неточности как они есть, по необходимости объясняя их в сносках

2020-11-09 12:08 UTC, Infl1ght approved these changes
Хорошая работа, спасибо!

2020-11-09 12:27 UTC, Infl1ght commented on Skunk Works. Личные мемуары моей работы в Локхид.fb2
> -      <p>Но соблазн постройки гиперзвукового самолёта был так велик, что он стал философским камнем для авиационных прожектёров. Идея всё ещё гуляет по Конгрессу, а её сторонники ищут финансирования,
В оригинале было именно про прожектёров, а не про индустрию в целом. Прожектёр - любитель несбыточных проектов (прожектов).

2020-11-09 12:32 UTC, Infl1ght approved these changes
Отличная работа, спасибо!

2020-11-09 12:32 UTC, Infl1ght commented on Skunk Works. Личные мемуары моей работы в Локхид.fb2
> +      <p>Я сблизился с Келли. Он потерял свою жену Алтею осенью 1970 года, после долгой борьбы с раком. Она была его ровесницей и когда-то была его секретарём. Ещё до своей смерти Алтея сказала Келли
Тут действительно, девушка рыжеволосая, а не красноволосая. Непонятно, как я это напереводил.
Но "Она была жизнерадостной, рыжеволосой девушкой" - лишняя запятая

2020-11-09 12:40 UTC, Infl1ght requested changes

2020-11-09 12:40 UTC, Infl1ght commented on Skunk Works. Личные мемуары моей работы в Локхид.fb2
> -      <p>До нескольких рабочих дошёл слух, что новые радиопоглощающие материалы содержат высокотоксичные вещества и они пожаловались, беспокоясь за своё здоровье. Мы очень осторожно относились к испо
Точно технический спирт?

2020-11-09 12:40 UTC, Infl1ght commented on Skunk Works. Личные мемуары моей работы в Локхид.fb2
> +      <p>Каким бы страшным Келли не казался, я знал, что ему будет далеко до моего строгого отца, Исидора Рича, британского гражданина, который был до начала Второй мировой войны управляющим лесопилк
Так лучше, только "введь" надо поправить

2020-11-09 18:17 UTC, Atarity commented on Skunk Works. Личные мемуары моей работы в Локхид.fb2
> -      <p>До нескольких рабочих дошёл слух, что новые радиопоглощающие материалы содержат высокотоксичные вещества и они пожаловались, беспокоясь за своё здоровье. Мы очень осторожно относились к испо
"Commercial" тут про "grade" продукта. Как "industrial grade" или "automotive grade". Нельзя ведь написать «полу-промышленный спирт».) В нашем языке мы обычно используем «технический спирт».

2020-11-09 18:26 UTC, Atarity commented on Skunk Works. Личные мемуары моей работы в Локхид.fb2
> +      <p>Каким бы страшным Келли не казался, я знал, что ему будет далеко до моего строгого отца, Исидора Рича, британского гражданина, который был до начала Второй мировой войны управляющим лесопилк
Починил

2020-11-09 18:26 UTC, Atarity commented on Skunk Works. Личные мемуары моей работы в Локхид.fb2
> +      <p>Я сблизился с Келли. Он потерял свою жену Алтею осенью 1970 года, после долгой борьбы с раком. Она была его ровесницей и когда-то была его секретарём. Ещё до своей смерти Алтея сказала Келли
Убрал

2020-11-11 09:35 UTC, merged